/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/health': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Readiness of the database and the model server */
    get: operations['HealthController_check'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/companies': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Every company in this installation */
    get: operations['CompaniesController_list'];
    put?: never;
    /** Register a company */
    post: operations['CompaniesController_create'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/sie/import': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Import a SIE4 file of accounts and historical verifications */
    post: operations['SieController_import'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/ledger/summary': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Counts and date range of the imported history */
    get: operations['LedgerController_summary'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/ledger/accounts': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** This company's chart of accounts */
    get: operations['LedgerController_accounts'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/ledger/verifications': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Imported verifications, newest first */
    get: operations['LedgerController_verifications'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/bank/import': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Import a bank CSV of transactions to be coded */
    post: operations['BankController_import'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/bank/transactions': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Imported bank transactions, newest first */
    get: operations['BankController_transactions'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/suggestions/generate': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Propose an entry for every transaction that has none */
    post: operations['SuggestionsController_generate'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/suggestions': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Transactions with their current proposal and entry preview */
    get: operations['SuggestionsController_list'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/suggestions/{transactionId}/decide': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Approve or correct a proposal, creating the journal entry */
    post: operations['SuggestionsController_decide'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    CreateCompanyDto: {
      /** @example Exempelbolaget AB */
      name: string;
      /**
       * @description Swedish organisation number
       * @example 556677-8899
       */
      orgNumber: string;
    };
    DecideDto: {
      /**
       * @description An account in this company's chart
       * @example 5420
       */
      accountNumber: string;
      /** @enum {string} */
      vatTreatment:
        | 'DOMESTIC_25'
        | 'DOMESTIC_12'
        | 'DOMESTIC_6'
        | 'REVERSE_CHARGE_EU'
        | 'REVERSE_CHARGE_NON_EU'
        | 'NONE';
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  HealthController_check: {
    parameters: {
      query?: never;
      header: {
        /** @description The company every scoped request is resolved against */
        'x-company-id': string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  CompaniesController_list: {
    parameters: {
      query?: never;
      header: {
        /** @description The company every scoped request is resolved against */
        'x-company-id': string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  CompaniesController_create: {
    parameters: {
      query?: never;
      header: {
        /** @description The company every scoped request is resolved against */
        'x-company-id': string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateCompanyDto'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  SieController_import: {
    parameters: {
      query?: never;
      header: {
        /** @description The company every scoped request is resolved against */
        'x-company-id': string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'multipart/form-data': {
          /** Format: binary */
          file?: string;
        };
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  LedgerController_summary: {
    parameters: {
      query?: never;
      header: {
        /** @description The company every scoped request is resolved against */
        'x-company-id': string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  LedgerController_accounts: {
    parameters: {
      query?: never;
      header: {
        /** @description The company every scoped request is resolved against */
        'x-company-id': string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  LedgerController_verifications: {
    parameters: {
      query?: {
        limit?: number;
      };
      header: {
        /** @description The company every scoped request is resolved against */
        'x-company-id': string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  BankController_import: {
    parameters: {
      query?: never;
      header: {
        /** @description The company every scoped request is resolved against */
        'x-company-id': string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'multipart/form-data': {
          /** Format: binary */
          file?: string;
        };
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  BankController_transactions: {
    parameters: {
      query?: {
        limit?: number;
      };
      header: {
        /** @description The company every scoped request is resolved against */
        'x-company-id': string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  SuggestionsController_generate: {
    parameters: {
      query?: {
        limit?: number;
      };
      header: {
        /** @description The company every scoped request is resolved against */
        'x-company-id': string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  SuggestionsController_list: {
    parameters: {
      query?: {
        limit?: number;
      };
      header: {
        /** @description The company every scoped request is resolved against */
        'x-company-id': string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  SuggestionsController_decide: {
    parameters: {
      query?: never;
      header: {
        /** @description The company every scoped request is resolved against */
        'x-company-id': string;
      };
      path: {
        transactionId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['DecideDto'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
}
